In [95]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [106]:
import torch
from PFNExperiments.Training.FlowMatching.Couplings import MiniBatchOTCoupling

In [137]:
z_0 = torch.randn(3, 1)
z_1 = torch.randn(3, 1)

In [148]:
z_0, z_1

(tensor([[-0.5612],
         [ 1.0427],
         [ 1.1003]]),
 tensor([[ 0.5392],
         [ 2.1905],
         [-0.1236]]))

In [139]:
torch.mean((z_0 - z_1) ** 2)

tensor(1.3422)

In [145]:
coupling = MiniBatchOTCoupling(
    solver = "emd",
    solver_params= {}
)

In [146]:
z_1_coupled = coupling.couple(z_0, z_1)

In [147]:
torch.mean((z_0 - z_1_coupled) ** 2)

tensor(0.5445)

In [149]:
z_0, z_1_coupled 

(tensor([[-0.5612],
         [ 1.0427],
         [ 1.1003]]),
 tensor([[-0.1236],
         [ 0.5392],
         [ 2.1905]]))